# SOURCE: https://install.portworx.com/?operator=true&mc=false&ns=portworx&b=true&kd=size%3D32&s=%22size%3D150%22&pureSanType=ISCSI&c=px-cluster-bf077f1e-9f71-4191-958f-25d9e4501657&stork=true&csi=true&mon=true&tel=true&st=k8s&promop=true
kind: StorageCluster
apiVersion: core.libopenstorage.org/v1
metadata:
  name: px-cluster-bf077f1e-9f71-4191-958f-25d9e4501657
  namespace: portworx
  annotations:
    portworx.io/install-source: "https://install.portworx.com/?operator=true&mc=false&ns=portworx&b=true&kd=size%3D32&s=%22size%3D150%22&pureSanType=ISCSI&c=px-cluster-bf077f1e-9f71-4191-958f-25d9e4501657&stork=true&csi=true&mon=true&tel=true&st=k8s&promop=true"
spec:
  image: portworx/oci-monitor:2.12.0
  imagePullPolicy: Always
  kvdb:
    internal: true
  cloudStorage:
    deviceSpecs:
    - size=150
    kvdbDeviceSpec: size=32
  secretsProvider: k8s
  stork:
    enabled: true
    args:
      webhook-controller: "true"
  autopilot:
    enabled: true
  csi:
    enabled: true
  monitoring:
    telemetry:
      enabled: true
    prometheus:
      enabled: true
      exportMetrics: true
  env:
  - name: PURE_FLASHARRAY_SAN_TYPE
    value: "ISCSI"
